FROM node:alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i

# 컨테이너 구동시 Volume을 사용하기 때문에 필요없는 COPY 삭제해도됨
# + Compose 에서 Volume mapping 으로 인한 COPY 불필요
COPY ./ ./
# CMD ["npm","start"] Compose에서 Command 추가로 인한 주석화